name = input("¿Cómo te llamas?")
degree = input("¿Cuál es tu nivel de estudios?")
current_focus = input("¿Qué estas estudiando?")
target = input("¿Cuál es tu objetivo?")
print (f"Name: {name}. Degree: {degree}. Current focus: {current_focus}. Target: {target} ")